[
    { name:"Turnips", Quantity: 076, Unit:"Pound", Description:"Root vegetable will grow in cold climates." },
    { name:"Watercress", Quantity: 076, Unit:"Pound", Description:"very peppery small salad like leaves" },
    { name:"Watermelon", Quantity: 076, Unit:"Pound", Description:"Sweet tasting gourd reaches enourmous size and definitely the most refreshing fruit there is." },
    { name:"Yams", Quantity: 076, Unit:"Pound", Description:"Sweet starchy tuber that are popular in African, Carribean and American cookery" },
    { name:"Artichoke", Quantity: 076, Unit:"Pound", Description:"tight head of fleshy leaves, delicious with lemon butter" },
    { name:"Asparagus", Quantity: 076, Unit:"Pound", Description:"tender green tips available during a short growing season" },
    { name:"Aubergene", Quantity: 076, Unit:"Pound", Description:"A rich purple vegetable that absorbs strong flavours well. The aubergene is called eggplant in America." },
    { name:"Beans", Quantity: 076, Unit:"Pound", Description:"high protien seeds of legume plants" },
    { name:"Beet", Quantity: 076, Unit:"Pound", Description:"Tubers with rich nutty flavours. A sweet variety of beet is grown commercially in europe and asia for sugar manufacture." },
    { name:"Broccoli", Quantity: 076, Unit:"Pound", Description:"green and delicious and full of vitamins" },
    { name:"Brussels sprouts", Quantity: 076, Unit:"Pound", Description:"traditionally eaten with Christmas Dinner in the UK" },
    { name:"Cabbage", Quantity: 076, Unit:"Pound", Description:"the king of vegetables. Easy to grow almost anywhere" },
    { name:"Carrot", Quantity: 076, Unit:"Pound", Description:"Introduced by the Romans, carrots have been popular for 2000 Years" },
    { name:"Cauliflower", Quantity: 076, Unit:"Pound", Description:"White relative of broccoli" },
    { name:"Celeriac", Quantity: 076, Unit:"Pound", Description:"a large knotted ball-like root vegetable which makes amazing nutty soups" },
    { name:"Celery", Quantity: 076, Unit:"Pound", Description:"Slightly bitter (unless blanched) european stalks with a distinctive flavour, used in salads, stews and soups." },
    { name:"Chard", Quantity: 076, Unit:"Pound", Description:"green leafy vegetable" },
    { name:"Chicory", Quantity: 076, Unit:"Pound", Description:"bitter vegetable" },
    { name:"Collards", Quantity: 076, Unit:"Pound", Description:"This leafy green vegetable is also known as tree-cabbage and is rich in vitamins and minerals." },
    { name:"Corn", Quantity: 076, Unit:"Pound", Description:"North American native vegetable considered sacred by many native tribes. Confusingly corn is also the word used to describe the seeds of wheat and barley." },
    { name:"Cress", Quantity: 076, Unit:"Pound", Description:"small peppery sprouts" },
    { name:"Cucumbers", Quantity: 076, Unit:"Pound", Description:"related to courgettes and traditionally used raw in salads. The cucumber grows quickly and holds lots of water" },
    { name:"Gourds", Quantity: 076, Unit:"Pound", Description:"The common name for fruits of the Cucurbitaceae family of plants (members include cucumbers, squashes, luffas, and melons)." },
    { name:"Jerusalem Artichoke", Quantity: 076, Unit:"Pound", Description:"It isn't an Artichoke and it doesn't come from Jerusalem. The jersalem Artichoke is actually related to the sunflower. The bit we eat is an ugly little tuber (like a small thin potato) that tastes amazing. It has a smoky taste that really excites the palette." },
    { name:"Kales", Quantity: 076, Unit:"Pound", Description:"Until the Renaissance, kale was the most common green vegetable eated by the people of northern Europe" },
    { name:"Kohlrabi", Quantity: 076, Unit:"Pound", Description:"Kohlrabi is a member of the turnip family and can be either purple or white." },
    { name:"Leek", Quantity: 076, Unit:"Pound", Description:"The national vegetable of Wales." },
    { name:"Lettuce", Quantity: 076, Unit:"Pound", Description:"lots of green leaves used as a mainstay of salads. Varieties such as round, isberg, lollo rosso and radichio are popular." },
    { name:"Melons", Quantity: 076, Unit:"Pound", Description:"Wonderful fruits with a high water content. There are many farmed varieties . All have seeds surrounded by rich, watery but sweet flesh that is encased in a fairly hard shell." },
    { name:"Mushrooms", Quantity: 076, Unit:"Pound", Description:"not technically a vegetable, but a far older member of the plant kingdom. Mushrooms do not use sunlight to produce energy, hence they have a completely different range of tastes than any other vegetable. Did you know that the largest single living organism on earth is a mushroom called Armillaria Ostoyae, the biggest of which is up to 8,500 years old and carpets nearly 10 square kilometres of forest floor in northeastern Oregon, USA." },
    { name:"Okra", Quantity: 076, Unit:"Pound", Description:"also called 'ladies fingers' or gumbo is a wonderful pungent vegetable from the same family as hollyhock. It probably was first cultivated in Ethiopia and is still a North African staple, but has become popular in Europe, Asia and America too." },
    { name:"Onions", Quantity: 076, Unit:"Pound", Description:"Onions have been eaten for tens of thousands of years and we still aren't bored of them. White and Red are the common colours for onions and they can vary in size from a few millimetres to almost a foot across." },
    { name:"Pak ChoiThe", Quantity: 076, Unit:"Pound", Description:"Pak Choi or chinese cabbage is a delicious leaf vegetable often used in Chinese cookery. It is a relative of the standard western cabbage but has a milder flavour and soft leaves." },
    { name:"Parsnips", Quantity: 076, Unit:"Pound", Description:"The sweet, starchy parsnip was a very popular european vegetable before the arrival of potaoes and Sugar Cane from the Americas. Although not the prize it once was, the Parsnip is a classic root vegetable, particularly popular in more northern lattitudes." },
    { name:"Peas", Quantity: 076, Unit:"Pound", Description:"best eated within minutes of picking as the sugars rapidly turn to starch. Therefore frozen peas often taste better than 'fresh' peas." },
    { name:"Peppers", Quantity: 076, Unit:"Pound", Description:"These are the fruit of the Capsicum family of plants. The hotter tasting ones (due to more Capsaicinoids in the flesh) are usually refered to as chillis." },
    { name:"Potatoes", Quantity: 076, Unit:"Pound", Description:"Nothing finer than a steaming plate of mashed potatoes. An american staple crop that as been exported all over the world." },
    { name:"Pumpkins", Quantity: 076, Unit:"Pound", Description:"A popular gourd vegetable used in cooking and to make halloween jack o lanterns." },
    { name:"Radicchio", Quantity: 076, Unit:"Pound", Description:"a chicory leaf used in salads. Popular since ancient times, modern widescale cultivation of the plant began in the fifteenth century close to Venice in Italy." },
    { name:"Radish", Quantity: 076, Unit:"Pound", Description:"rich in ascorbic acid (vitamin C), folic acid (folate), and Potassium, the raddish is a peppery vegetable popular in western and asian cookery. We usually eat the taproot, but the leaves can also be eaten in salads." },
    { name:"Rhubarb", Quantity: 076, Unit:"Pound", Description:"A plant with large leaves that grow out of thick succulent stems with a very particular floral scent. These stems are popularly eaten as a fruit once sweetened and cooked. Rhubarb was originally native to China but has been popular in Europe since Roman times." },
    { name:"Rutabaga", Quantity: 076, Unit:"Pound", Description:"Alternative name for Swede" },
    { name:"Shallots", Quantity: 076, Unit:"Pound", Description:"Small onions often with a more fiery bite." },
    { name:"Spinach", Quantity: 076, Unit:"Pound", Description:"large green leaves wilt easily in a pan and are often served with a little butter and nutmeg as an accompanying vegetable. Spinach contains lots of healthy trace minerals including iron" },
    { name:"Squash", Quantity: 076, Unit:"Pound", Description:"another generic name for fruits of the vine of the Cucurbitaceae family of plants (see also Gourds). Butternut Squash has recently grown in popularity in the United Kingdom." },
    { name:"Swede", Quantity: 076, Unit:"Pound", Description:"Apparently a cross between cabbages and turnips swedes are a low calory root vegetable" },
    { name:"Sweetcorn", Quantity: 076, Unit:"Pound", Description:"a north american native plant loved throughout the world." },
    { name:"Sweet", Quantity: 076, Unit:"Pound", Description:"potato Ipomoea batatas (related to the morning glory) produces a starchy tuber. In the USA the red variety of sweet potato is often called a yam, although yams are a seperate vegetable in their own right." },
    { name:"Tomatoes", Quantity: 076, Unit:"Pound", Description:"not technically a vegetable, but a fruit. Tomatoes are best grown yourself because the uniform flavourless powdery fruits available in supermarkets are not worth eating." },								 
]